---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: get-started
  label: Let's Get Started
- type: document
  path: our-team
  label: Our Team
- type: document
  path: faq
  label: FAQs
- type: document
  path: how-lw-works
  label: How LivingWisely Works
- type: document
  path: home
  label: Home
- type: directory
  path: organizations
  label: Organizations
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
